<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.219 (mame0219)" debug="no" mameconfig="10">
	<machine name="005" sourcefile="segag80r.cpp" sampleof="005">
		<description>005</description>
		<year>1981</year>
		<manufacturer>Sega</manufacturer>
		<rom name="1346b.cpu-u25" size="2048" crc="8e68533e" sha1="a257c556d31691068ed5c991f1fb2b51da4826db" region="maincpu" offset="0"/>
		<rom name="5092.prom-u1" size="2048" crc="29e10a81" sha1="c4b4e6c75bcf276e53f39a456d8d633c83dcf485" region="maincpu" offset="800"/>
		<rom name="5093.prom-u2" size="2048" crc="e1edc3df" sha1="4f593546bbb0f50850dc6286cb514af6831c27a7" region="maincpu" offset="1000"/>
		<rom name="5094.prom-u3" size="2048" crc="995773bb" sha1="98dd826527853bc031edfb9a821778cc3e906150" region="maincpu" offset="1800"/>
		<rom name="5095.prom-u4" size="2048" crc="f887f575" sha1="de96573a91b60b090b1f441f1410ecad63c9467c" region="maincpu" offset="2000"/>
		<rom name="5096.prom-u5" size="2048" crc="5545241e" sha1="ee504ccaab469100137717341a1b461175ff792d" region="maincpu" offset="2800"/>
		<rom name="5097.prom-u6" size="2048" crc="428edb54" sha1="4f3df6017068d939014a8f638f28e3228acb7add" region="maincpu" offset="3000"/>
		<rom name="5098.prom-u7" size="2048" crc="5bcb9d63" sha1="c0c91bc9f75ad88a6e15c554a980d5c075725fe8" region="maincpu" offset="3800"/>
		<rom name="5099.prom-u8" size="2048" crc="0ea24ba3" sha1="95a30c9b63ef1c346df0da71af3fdecd1a75cb8f" region="maincpu" offset="4000"/>
		<rom name="5100.prom-u9" size="2048" crc="a79af131" sha1="0ba34130174e196015bc9b9c135c420209dfd524" region="maincpu" offset="4800"/>
		<rom name="5101.prom-u10" size="2048" crc="8a1cdae0" sha1="f7c617f9bdb7818e6069a981d0c8820deade134c" region="maincpu" offset="5000"/>
		<rom name="5102.prom-u11" size="2048" crc="70826a15" sha1="a86322d0e8a88534e9b78dcde42ae4c441276913" region="maincpu" offset="5800"/>
		<rom name="5103.prom-u12" size="2048" crc="7f80c5b0" sha1="00748cd5fc7f75fdca194e748524d406c006296d" region="maincpu" offset="6000"/>
		<rom name="5104.prom-u13" size="2048" crc="0140930e" sha1="f8ef894c46d3663bd89d2d817675a67075d3e0d6" region="maincpu" offset="6800"/>
		<rom name="5105.prom-u14" size="2048" crc="17807a05" sha1="bd99f5beab0155f6e4d2fab2fa5f4e147c5730d5" region="maincpu" offset="7000"/>
		<rom name="5106.prom-u15" size="2048" crc="c7cdfa9d" sha1="6ab7adc60ac7bb53a7175e8de51924008737c9ac" region="maincpu" offset="7800"/>
		<rom name="5107.prom-u16" size="2048" crc="95f8a2e6" sha1="89c92e000b3e1630380db779370cf9f5b13e5719" region="maincpu" offset="8000"/>
		<rom name="5108.prom-u17" size="2048" crc="d371cacd" sha1="8f2cdcc0b4e3b77e0958d257e37accefc5749cde" region="maincpu" offset="8800"/>
		<rom name="5109.prom-u18" size="2048" crc="48a20617" sha1="5b4bc3beda0404ff0a61bb42751b87f71817f363" region="maincpu" offset="9000"/>
		<rom name="5110.prom-u19" size="2048" crc="7d26111a" sha1="a6d3652ae606a5b75026e524c9d6aaa78300741e" region="maincpu" offset="9800"/>
		<rom name="5111.prom-u20" size="2048" crc="a888e175" sha1="4c0af94441bf51dfc852372a5b90d0830df81363" region="maincpu" offset="a000"/>
		<rom name="epr-1286.sound-16" size="2048" crc="fbe0d501" sha1="bfa277689790f835d8a43be4beee0581e1096bcc" region="005" offset="0"/>
		<rom name="6331.sound-u8" size="32" crc="1d298cb0" sha1="bb0bb62365402543e3154b9a77be9c75010e6abc" status="baddump" region="proms" offset="0"/>
		<device_ref name="z80"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="screen"/>
		<device_ref name="speaker"/>
		<device_ref name="i8255"/>
		<device_ref name="samples"/>
		<device_ref name="sega005_sound"/>
		<sample name="lexplode"/>
		<sample name="sexplode"/>
		<sample name="dropbomb"/>
		<sample name="shoot"/>
		<sample name="missile"/>
		<sample name="helicopt"/>
		<sample name="whistle"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="3867120"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="samples" name="Samples"/>
		<chip type="audio" tag="005" name="Sega 005 Custom Sound"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" pixclock="5156160" htotal="328" hbend="0" hbstart="256" vtotal="262" vbend="0" vbstart="224" />
		<sound channels="1"/>
		<input players="2" coins="2" service="yes">
			<control type="joy" player="1" buttons="1" ways="4"/>
			<control type="joy" player="2" buttons="1" ways="4"/>
		</input>
		<dipswitch name="Coin A" tag="D1D0" mask="15">
			<diplocation name="SW2" number="8"/>
			<diplocation name="SW2" number="7"/>
			<diplocation name="SW2" number="6"/>
			<diplocation name="SW2" number="5"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="9"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="10"/>
			<dipvalue name="1 Coin/1 Credit" value="3" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="11"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="12"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="13"/>
			<dipvalue name="1 Coin/2 Credits" value="4"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="14"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="15"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="6"/>
			<dipvalue name="1 Coin/5 Credits" value="7"/>
			<dipvalue name="1 Coin/6 Credits" value="8"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="D1D0" mask="240">
			<diplocation name="SW2" number="4"/>
			<diplocation name="SW2" number="3"/>
			<diplocation name="SW2" number="2"/>
			<diplocation name="SW2" number="1"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="16"/>
			<dipvalue name="2 Coins/1 Credit" value="32"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="144"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="160"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="176"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="192"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="208"/>
			<dipvalue name="1 Coin/2 Credits" value="64"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="224"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="240"/>
			<dipvalue name="1 Coin/3 Credits" value="80"/>
			<dipvalue name="1 Coin/4 Credits" value="96"/>
			<dipvalue name="1 Coin/5 Credits" value="112"/>
			<dipvalue name="1 Coin/6 Credits" value="128"/>
		</dipswitch>
		<dipswitch name="Lives" tag="D3D2" mask="3">
			<diplocation name="SW1" number="8"/>
			<diplocation name="SW1" number="7"/>
			<dipvalue name="3" value="0" default="yes"/>
			<dipvalue name="4" value="2"/>
			<dipvalue name="5" value="1"/>
			<dipvalue name="6" value="3"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="D3D2" mask="4">
			<diplocation name="SW1" number="6"/>
			<dipvalue name="Upright" value="4" default="yes"/>
			<dipvalue name="Cocktail" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="8">
			<diplocation name="SW1" number="5"/>
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="16">
			<diplocation name="SW1" number="4"/>
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="32">
			<diplocation name="SW1" number="3"/>
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="64">
			<diplocation name="SW1" number="2"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="D3D2" mask="128">
			<diplocation name="SW1" number="1"/>
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<port tag=":D1D0">
		</port>
		<port tag=":D3D2">
		</port>
		<port tag=":D5D4">
		</port>
		<port tag=":D7D6">
		</port>
		<port tag=":FC">
		</port>
		<port tag=":SERVICESW">
		</port>
		<driver status="imperfect" emulation="good" savestate="unsupported"/>
		<feature type="sound" status="imperfect"/>
	</machine>
	<machine name="100lions" sourcefile="aristmk6.cpp" romof="aristmk6">
		<description>100 Lions (10219211, NSW/ACT)</description>
		<year>2006</year>
		<manufacturer>Aristocrat</manufacturer>
		<biosset name="au-nsw1" description="Aristocrat MK6 Base (02010114, NSW/ACT)"/>
		<biosset name="au-nsw2" description="Aristocrat MK6 Base (02010201, NSW/ACT)"/>
		<biosset name="au-nsw3" description="Aristocrat MK6 Base (02061013, NSW/ACT)"/>
		<biosset name="au-nsw4" description="Aristocrat MK6 Base (03010301, NSW/ACT)"/>
		<biosset name="au-nsw5" description="Aristocrat MK6 Base (04010501, NSW/ACT)"/>
		<biosset name="au-nsw6" description="Aristocrat MK6 Base (05010601, NSW/ACT)"/>
		<biosset name="au-nsw7" description="Aristocrat MK6 Base (07010801, NSW/ACT)"/>
		<biosset name="au-nsw8" description="Aristocrat MK6 Base (09011001, NSW/ACT)"/>
		<biosset name="au-nsw9" description="Aristocrat MK6 Base (11011501, NSW/ACT)"/>
		<biosset name="au-nsw10" description="Aristocrat MK6 Base (11011901, NSW/ACT)"/>
		<biosset name="au-nsw11" description="Aristocrat MK6 Base (13012001, NSW/ACT)"/>
		<biosset name="au-nsw12" description="Aristocrat MK6 Base (14011913, NSW/ACT)"/>
		<biosset name="au-nsw13" description="Aristocrat MK6 Base (19012801, NSW/ACT)"/>
		<biosset name="au-nsw14" description="Aristocrat MK6 Base (21012901, NSW/ACT)"/>
		<biosset name="au-nsw15" description="Aristocrat MK6 Base (24013001, NSW/ACT)"/>
		<biosset name="au-sa1" description="Aristocrat MK6 Base (03030708, South Australia)"/>
		<biosset name="my" description="Aristocrat MK6 Base (15011025, Malaysia)"/>
		<biosset name="au-qld1" description="Aristocrat MK6 Base (14011605, Queensland))"/>
		<biosset name="au-qld2" description="Aristocrat MK6 Base (20012305, Queensland)"/>
		<biosset name="au-qld3" description="Aristocrat MK6 Base (20012605, Queensland)"/>
		<biosset name="au-qld4" description="Aristocrat MK6 Base (01040505, Queensland)"/>
		<biosset name="au-qld5" description="Aristocrat MK6 Base (04041205, Queensland)"/>
		<biosset name="au-qld6" description="Aristocrat MK6 Base (03130334, Queensland)"/>
		<biosset name="au-qld7" description="Aristocrat MK6 Base (25012805, Queensland)"/>
		<biosset name="us1" description="Aristocrat MK6 Base (01.02.08, USA)"/>
		<biosset name="us2" description="Aristocrat MK6 Base (01.03.03a, USA)"/>
		<biosset name="us3" description="Aristocrat MK6 Base (01.03.03e, USA)"/>
		<biosset name="us4" description="Aristocrat MK6 Base (01.03.05, USA)"/>
		<biosset name="us5" description="Aristocrat MK6 Base (01.03.06, USA)"/>
		<biosset name="us6" description="Aristocrat MK6 Base (01.03.07, USA)"/>
		<biosset name="us7" description="Aristocrat MK6 Base (01.03.14, USA)"/>
		<biosset name="us8" description="Aristocrat MK6 Base (01.03.17, USA)"/>
		<biosset name="us9" description="Aristocrat MK6 Base (01.04.14, USA)"/>
		<biosset name="us10" description="Aristocrat MK6 Base (01.04.07, USA)"/>
		<biosset name="us11" description="Aristocrat MK6 Base (01.04.08, USA)"/>
		<biosset name="us12" description="Aristocrat MK6 Base (01.04.10, USA)"/>
		<biosset name="us13" description="Aristocrat MK6 Base (01.04.11, USA)"/>
		<biosset name="set-us1" description="Aristocrat MK6 Set Chips (06.02.04, USA)"/>
		<biosset name="set-us2" description="Aristocrat MK6 Set Chips (06.02.20, USA)"/>
		<biosset name="set-us3" description="Aristocrat MK6 Set Chips (06.03.03, USA)"/>
		<biosset name="set-us4" description="Aristocrat MK6 Set Chips (06.03.04, USA)"/>
		<rom name="02010114.u84" merge="02010114.u84" bios="au-nsw1" size="1048576" crc="183e3836" sha1="4c802d0cd010bc007acb3a83e37aaa29b2d13d87" region="maincpu" offset="0"/>
		<rom name="02010114.u71" merge="02010114.u71" bios="au-nsw1" size="1048576" crc="8f83c3dd" sha1="a5f9d80b4b515b24299d0241e1665cfd9da8bab7" region="maincpu" offset="2"/>
		<rom name="02010114.u83" merge="02010114.u83" bios="au-nsw1" size="1048576" crc="945104d7" sha1="e372d0cf889c72b5d001b26fe4a925a28486537f" region="maincpu" offset="4"/>
		<rom name="02010114.u70" merge="02010114.u70" bios="au-nsw1" size="1048576" crc="3ba4379f" sha1="84367f12c4c9224d2ab9cae83ae8727de338408c" region="maincpu" offset="6"/>
		<rom name="02010201.u84" merge="02010201.u84" bios="au-nsw2" size="1048576" crc="0920930f" sha1="771b0f62442d1c75b1bb59ad82365b7ab8747173" region="maincpu" offset="0"/>
		<rom name="02010201.u71" merge="02010201.u71" bios="au-nsw2" size="1048576" crc="24d5614a" sha1="fdcf3826dccc72b74b66379b1411cf211d5a1670" region="maincpu" offset="2"/>
		<rom name="02010201.u83" merge="02010201.u83" bios="au-nsw2" size="1048576" crc="5f64a20c" sha1="397404ab6d2a1aa3c1fc77bb9421fef7079b65a5" region="maincpu" offset="4"/>
		<rom name="02010201.u70" merge="02010201.u70" bios="au-nsw2" size="1048576" crc="9b2db442" sha1="d512398a2d9257bd385dc50d61c63cd1a47300ba" region="maincpu" offset="6"/>
		<rom name="02061013_right.u83" merge="02061013_right.u83" bios="au-nsw3" size="1048576" crc="7a8619a5" sha1="bd03ddb68817c1660b009e102ccf69e5b603b875" region="maincpu" offset="0"/>
		<rom name="02061013_left.u70" merge="02061013_left.u70" bios="au-nsw3" size="1048576" crc="e70a7007" sha1="0935f924866162d9c0fbdbb99391cbf730a04b76" region="maincpu" offset="2"/>
		<rom name="03010301.u84" merge="03010301.u84" bios="au-nsw4" size="1048576" crc="a34a9f16" sha1="b8750e6ceb1715da8e5ac2f0183254e29a042641" region="maincpu" offset="0"/>
		<rom name="03010301.u71" merge="03010301.u71" bios="au-nsw4" size="1048576" crc="d793440a" sha1="dced4c04bde13293af77a9a1f4c5c606e3758de0" region="maincpu" offset="2"/>
		<rom name="03010301.u83" merge="03010301.u83" bios="au-nsw4" size="1048576" crc="c8580554" sha1="58b8bfff2f8d298c4e3be2b01900800c45fa7ad7" region="maincpu" offset="4"/>
		<rom name="03010301.u70" merge="03010301.u70" bios="au-nsw4" size="1048576" crc="5ae69121" sha1="36dd3f9aaf5f7d2751d1954d67f898bc3ec71f3b" region="maincpu" offset="6"/>
		<rom name="04010501_right.u83" merge="04010501_right.u83" bios="au-nsw5" size="1048576" crc="3daefb7a" sha1="411471713219f4bab5ccf5fe7a12a6c138c8c550" region="maincpu" offset="0"/>
		<rom name="04010501_left.u70" merge="04010501_left.u70" bios="au-nsw5" size="1048576" crc="21182775" sha1="7c5b7f5aba3babc85f512a8f7d4ebc0d83eb842a" region="maincpu" offset="2"/>
		<rom name="05010601_right.u83" merge="05010601_right.u83" bios="au-nsw6" size="1048576" crc="c12eac11" sha1="683b9ddc323865ace7dca37d13b55de6e42759a5" region="maincpu" offset="0"/>
		<rom name="05010601_left.u70" merge="05010601_left.u70" bios="au-nsw6" size="1048576" crc="b3e6b4a0" sha1="3bf398c9257579f8e51ce716d6ebfa74fa510273" region="maincpu" offset="2"/>
		<rom name="07010801_right.u83" merge="07010801_right.u83" bios="au-nsw7" size="2097152" crc="8c148c11" sha1="5ff3be18455b4f04675fec8d5b9d881295c65e23" region="maincpu" offset="0"/>
		<rom name="07010801_left.u70" merge="07010801_left.u70" bios="au-nsw7" size="2097152" crc="8e92af68" sha1="00d2bb655b7964a9652896741210ec534df0b0d2" region="maincpu" offset="2"/>
		<rom name="09011001_right.u83" merge="09011001_right.u83" bios="au-nsw8" size="2097152" crc="8a853f80" sha1="9a75498f7b02c81a483b4e1c158f35f0ee4c0112" region="maincpu" offset="0"/>
		<rom name="09011001_left.u70" merge="09011001_left.u70" bios="au-nsw8" size="2097152" crc="229c2e63" sha1="91fd2b1acb69efe073647e93db9f11042add2feb" region="maincpu" offset="2"/>
		<rom name="11011501_right.u83" merge="11011501_right.u83" bios="au-nsw9" size="2097152" crc="de4c3aed" sha1="21596a2edd20eb7de7a4ec8900a270b09c8f326f" region="maincpu" offset="0"/>
		<rom name="11011501_left.u70" merge="11011501_left.u70" bios="au-nsw9" size="2097152" crc="c5cc3461" sha1="5b43c4cb6110a6ccf67cd0f3789253f6872b20c4" region="maincpu" offset="2"/>
		<rom name="11011901_right.u83" merge="11011901_right.u83" bios="au-nsw10" size="2097152" crc="73dcb11c" sha1="69ae4f32a0c9141b2a82ff3935b0cd20333d2964" region="maincpu" offset="0"/>
		<rom name="11011901_left.u70" merge="11011901_left.u70" bios="au-nsw10" size="2097152" crc="d3dd2210" sha1="3548f8cc39859d3f44a55f6bae48966a2d48e0eb" region="maincpu" offset="2"/>
		<rom name="13012001_right.u83" merge="13012001_right.u83" bios="au-nsw11" size="2097152" crc="e627dbfa" sha1="4fedbe0975ceb7dc0ebebf18a7708d78984db9b7" region="maincpu" offset="0"/>
		<rom name="13012001_left.u70" merge="13012001_left.u70" bios="au-nsw11" size="2097152" crc="38e8f659" sha1="88c6acba99b0aca023c6f4d27c061c231490e9e0" region="maincpu" offset="2"/>
		<rom name="14011913_right.u83" merge="14011913_right.u83" bios="au-nsw12" size="2097152" crc="01d13b89" sha1="b1013366d0803dfbec5a5f90f6a5cea862de0513" region="maincpu" offset="0"/>
		<rom name="14011913_left.u70" merge="14011913_left.u70" bios="au-nsw12" size="2097152" crc="9a4cefdf" sha1="6c15bc565ede8af19361d60ee1e6657a8055c92c" region="maincpu" offset="2"/>
		<rom name="19012801_right.u83" merge="19012801_right.u83" bios="au-nsw13" size="2097152" crc="5b20a96c" sha1="5fd916b7cc2cdd51bf7dd212c1114f94dc9c7926" region="maincpu" offset="0"/>
		<rom name="19012801_left.u70" merge="19012801_left.u70" bios="au-nsw13" size="2097152" crc="b03bd17c" sha1="f281e80f6dda5b727ed71d2deebe3b0ff548773f" region="maincpu" offset="2"/>
		<rom name="21012901_right.u83" merge="21012901_right.u83" bios="au-nsw14" size="2097152" crc="757618f2" sha1="43f9a3e7d544979f8c6974945914d9e099b02abd" region="maincpu" offset="0"/>
		<rom name="21012901_left.u70" merge="21012901_left.u70" bios="au-nsw14" size="2097152" crc="0d271470" sha1="5cd4b604bfe2fd7e9a8d08e1c7c97f17ae068479" region="maincpu" offset="2"/>
		<rom name="24013001_right.u83" merge="24013001_right.u83" bios="au-nsw15" size="2097152" crc="e97afedf" sha1="10ca3b015afaff5d7812f0f5207b2535602136a5" region="maincpu" offset="0"/>
		<rom name="24013001_left.u70" merge="24013001_left.u70" bios="au-nsw15" size="2097152" crc="06ae7e07" sha1="39a45575b66906d73b519988d1001c99b05c5f34" region="maincpu" offset="2"/>
		<rom name="03030708_right.u83" merge="03030708_right.u83" bios="au-sa1" size="1048576" crc="b4b3c6a5" sha1="5747f98a6eaa5c24a23d1d76a28b33a3bfbbfd1f" region="maincpu" offset="0"/>
		<rom name="03030708_left.u70" merge="03030708_left.u70" bios="au-sa1" size="1048576" crc="4e5ad823" sha1="77ab1c29c6172cfdcef776222a72b2b44114d4da" region="maincpu" offset="2"/>
		<rom name="15011025_right.u83" merge="15011025_right.u83" bios="my" size="2097152" crc="bf21a975" sha1="a251b1a7342387300689cd50fe4ce7975b903ac5" region="maincpu" offset="0"/>
		<rom name="15011025_left.u70" merge="15011025_left.u70" bios="my" size="2097152" crc="c02e14b0" sha1="6bf98927813519dfe60e582dbe5be3ccd87f7c91" region="maincpu" offset="2"/>
		<rom name="14011605_right.u83" merge="14011605_right.u83" bios="au-qld1" size="2097152" crc="2bec5b74" sha1="854733cada75e632f01f7096d4740ed4941a3d5b" region="maincpu" offset="0"/>
		<rom name="14011605_left.u70" merge="14011605_left.u70" bios="au-qld1" size="2097152" crc="cd26d4f0" sha1="40822714abf08aeb08d827dbd8cd099f86803754" region="maincpu" offset="2"/>
		<rom name="20012305_right.u83" merge="20012305_right.u83" bios="au-qld2" size="2097152" crc="e436c1f5" sha1="62ee529cc971fd76aa2ccc15778e3f0c40e3e47f" region="maincpu" offset="0"/>
		<rom name="20012305_left.u70" merge="20012305_left.u70" bios="au-qld2" size="2097152" crc="ea8961cc" sha1="0ebc7c3b94a6e01ee984af4711043130d9670bd3" region="maincpu" offset="2"/>
		<rom name="20012605_right.u83" merge="20012605_right.u83" bios="au-qld3" size="2097152" crc="045b82ad" sha1="b8e4f9f826970d83ae5fd2f2898de12ad1bf2d24" region="maincpu" offset="0"/>
		<rom name="20012605_left.u70" merge="20012605_left.u70" bios="au-qld3" size="2097152" crc="87331111" sha1="6cdc2d81f68de23af18a975a6f27ddec246be405" region="maincpu" offset="2"/>
		<rom name="01040505.u84" merge="01040505.u84" bios="au-qld4" size="1048576" crc="cf5a9d1e" sha1="0ebba478fc883831d70b0fa95f43e5f93b07ae9e" region="maincpu" offset="0"/>
		<rom name="01040505.u71" merge="01040505.u71" bios="au-qld4" size="1048576" crc="f56ea77e" sha1="319be1bee66a289e2c1f6beec07758f79aa0cf16" region="maincpu" offset="2"/>
		<rom name="01040505.u83" merge="01040505.u83" bios="au-qld4" size="1048576" crc="90f32169" sha1="228be8b4a9eb6b2acf7f7a7561bd194009936026" region="maincpu" offset="4"/>
		<rom name="01040505.u70" merge="01040505.u70" bios="au-qld4" size="1048576" crc="b9ddea66" sha1="f4bfdeada39a3f0094d6468b7374a34f88f5df7f" region="maincpu" offset="6"/>
		<rom name="04041205_right.u83" merge="04041205_right.u83" bios="au-qld5" size="1048576" crc="ca6bc86c" sha1="69fe7fc35694e4cd7f861bff4ec3a6165a81df6e" region="maincpu" offset="0"/>
		<rom name="04041205_left.u70" merge="04041205_left.u70" bios="au-qld5" size="1048576" crc="dfb9a119" sha1="814a5a7877392aec4e4871d7f0e19d2fbd717409" region="maincpu" offset="2"/>
		<rom name="03130334_right.u83" merge="03130334_right.u83" bios="au-qld6" size="2097152" crc="bce3d97f" sha1="da36377cc1465022a2434703adee63bf48c71a9c" region="maincpu" offset="0"/>
		<rom name="03130334_left.u70" merge="03130334_left.u70" bios="au-qld6" size="2097152" crc="02175fde" sha1="4e9a9e1e803a0c84b06aec99dc3147dd7a919eee" region="maincpu" offset="2"/>
		<rom name="25012805_right.u83" merge="25012805_right.u83" bios="au-qld7" size="2097152" crc="2ecd8da8" sha1="389e9668b2ba4fffed5d2721b2ce70d502fb9f67" region="maincpu" offset="0"/>
		<rom name="25012805_left.u70" merge="25012805_left.u70" bios="au-qld7" size="2097152" crc="996f32ce" sha1="cf21bef745986fcbd298167453c7b8e5945ce602" region="maincpu" offset="2"/>
		<rom name="01.02.08_right.u2" merge="01.02.08_right.u2" bios="us1" size="1048576" crc="aaaeac8c" sha1="a565e5fcb4f55f31e7d36be40eec234248a66efd" region="maincpu" offset="0"/>
		<rom name="01.02.08_left.u3" merge="01.02.08_left.u3" bios="us1" size="1048576" crc="f29fd1bf" sha1="33e043d2616e10a1c7a0936c3d208f9bcc2ca6f3" region="maincpu" offset="2"/>
		<rom name="01.03.03a_right.u83" merge="01.03.03a_right.u83" bios="us2" size="2097152" crc="253415f4" sha1="50dc77ad87bc6be1932dda2fd4865602c8c49729" region="maincpu" offset="0"/>
		<rom name="01.03.03a_left.u70" merge="01.03.03a_left.u70" bios="us2" size="2097152" crc="4ab5dd40" sha1="a6812cc624e6a98ea7b0697e2797fe10ba8e303e" region="maincpu" offset="2"/>
		<rom name="01.03.03e_right.u83" merge="01.03.03e_right.u83" bios="us3" size="2097152" crc="2255e263" sha1="5e9e093aaa17172f47a14c3baf7f6f0f73b19398" region="maincpu" offset="0"/>
		<rom name="01.03.03e_left.u70" merge="01.03.03e_left.u70" bios="us3" size="2097152" crc="ea50729a" sha1="14b5a71bfb91ac366ddcb5f77fb54127808f8163" region="maincpu" offset="2"/>